### PR TITLE
Conflict of copyright?

### PR DESCRIPTION
**Pull request by pikesley**
```
(C) AMEE 
```

and

```
MIT Licensed
```

is that correct?

### CODE REVIEW

**Comment by Floppy** [comment]
No, MIT license doesn't affect copyright. It simply specifies what reuse you allow. See https://en.wikipedia.org/wiki/MIT_License#License_terms

**Comment by mrchrisadams** [comment]
So, a bit like `deny/allow` rules in Apache conf files…

**Comment by Floppy** [comment]
er

**Comment by Floppy** [comment]
maybe. _nods and smiles_

**Comment by mrchrisadams** [comment]
This isn't a conflict, but could be clearer, because normally the copyright line is part of the MIT licence, and in this case, it's listed in the COPYING file.

My mental model of it was this:  copyright retains all rights, as a precaution, then you use the MIT license to open the rights back up, as long as the initial license is attached to this data set.

Andrew Berkeley (@spatchcock) opened this while an employee of AMEE, so I expect the change we might want to make here is to update the COPYING file to reflect the copyright claim there to AMEE's one, to bring it into line with the readme file here.

Thoughts?

https://github.com/AMEE/datasets/blob/master/COPYING#L1
https://github.com/AMEE/datasets/blob/master/COPYING#L10

**Comment by Floppy** [comment]
Sounds about right. It should be AMEE in the copyright line at the top, yes.

**Pull request closed without merging**
